# Generated by Django 2.2.2 on 2019-06-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toppage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('article', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'toppage',
                'db_table': 'toppage',
            },
        ),
    ]
